Add support for Avro reads
GoogleCloudDataproc/hive-bigquery-connector pull request #8
Opened 2022-05-27 04:48 UTC by jphalip

2022-06-07 01:26 UTC, VinayLondhe14 approved these changes

2022-06-27 23:16 UTC, davidrabinowitz requested changes

2022-06-28 00:00 UTC, jphalip commented on connector/src/main/java/com/google/cloud/hive/bigquery/connector/utils/avro/AvroUtils.java
> +    if (schemaInfo.actualSchema.getType() == Type.UNION) {
Not really useful here

2022-07-12 23:13 UTC, davidrabinowitz commented
/gcbrun

2022-07-12 23:13 UTC, davidrabinowitz approved these changes

2022-07-25 17:08 UTC, merged